name: CDKTF Documentation
on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  cdktfDocs:
    uses: hashicorp/terraform-cdk/.github/workflows/registry-docs-pr-based.yml@06a417e5856a87a01664e12ddfb8edd8160cafc3
    secrets:
      GH_PR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      providerFqn: "hashicorp/aws"
      files: "*/ec2_*.html.markdown"
