name: CDKTF Documentation
on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  cdktfDocs:
    uses: hashicorp/terraform-cdk/.github/workflows/registry-docs-pr-based.yml@98e05c55799802e5457fddc8d69a1c5c6a5f6e0b
    secrets:
      GH_PR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      providerFqn: "hashicorp/aws"
      files: "*/ec2_*.html.markdown"
