name: CDKTF Documentation
on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch: {}

jobs:
  cdktfDocs:
    uses: hashicorp/cdktf-registry-docs/.github/workflows/pr-based-rollout.yml@214d7d9273e8540bc281a92a425c9b2d0436dfd9
    secrets:
      GH_PR_TOKEN: ${{ secrets.TF_WORKFLOW_GITHUB_TOKEN }}
    with:
      providerFqn: "hashicorp/aws"
      files: "*/ec2_*.html.markdown"
