name: CDKTF Documentation
on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch: {}

jobs:
  cdktfDocs:
    uses: hashicorp/terraform-cdk/.github/workflows/registry-docs-pr-based.yml@d16156be98c1d0d25b88c520284875aa92e165cd
    secrets:
      GH_PR_TOKEN: ${{ secrets.TF_WORKFLOW_GITHUB_TOKEN }}
    with:
      providerFqn: "hashicorp/aws"
      files: "*/ec2_*.html.markdown"
